export const Users = [
  {
    id: 1,
    profilePicture: '/assets/1.jpg',
    username: 'Joe Dev',
  },
  {
    id: 2,
    profilePicture: '/assets/2.jpg',
    username: 'Arsalan Ahmed',
  },
  {
    id: 3,
    profilePicture: '/assets/3.jpg',
    username: 'Ahmed Khalid',
  },
  {
    id: 4,
    profilePicture: '/assets/4.jpg',
    username: 'Mushahid Khan',
  },
  {
    id: 5,
    profilePicture: '/assets/IMG_0032.JPG',
    username: 'Joe Biden rathore',
  },
  {
    id: 6,
    profilePicture: '/assets/IMG_0062.JPG',
    username: 'Lion Nawaz',
  },
  {
    id: 7,
    profilePicture: '/assets/IMG_0366.JPG',
    username: 'Tato Bachaa',
  },
  {
    id: 8,
    profilePicture: '/assets/IMG_0600.JPG',
    username: 'Kite Shareef UnShareef',
  },
  {
    id: 9,
    profilePicture: '/assets/IMG_0601.JPG',
    username: 'Shah rukh khan',
  },
  {
    id: 10,
    profilePicture: '/assets/a.JPG',
    username: 'Banda e khuda',
  },
]
export const Posts = [
  {
    id: 1,
    desc: 'Love For All, Hatred For None.',
    photo: '/assets/posts/1.jpg',
    date: 'just now',
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: 'Hey guys, enjoy my new song!',
    photo: '/assets/posts/2.jpg',
    date: '10 mins ago',
    userId: 2,
    like: 2,
    comment: 10,
  },
  {
    id: 3,
    desc: 'New World Order',
    photo: '/assets/posts/3.jpg',
    date: '15 mins ago',
    userId: 3,
    like: 23,
    comment: 19,
  },
  {
    id: 4,
    desc: 'Wonderful day with my family!',
    photo: '/assets/posts/4.jpg',
    date: '13 mins ago',
    userId: 4,
    like: 0,
    comment: 0,
  },
  {
    id: 5,
    desc: 'Life is cool',
    photo: '/assets/posts/5.jpg',
    date: '50 mins ago',
    userId: 5,
    like: 320,
    comment: 90,
  },
  {
    id: 6,
    desc: 'Freedom is power',
    photo: '/assets/posts/6.jpg',
    date: '52 mins ago',
    userId: 6,
    like: 320,
    comment: 0,
  },
  {
    id: 7,
    desc: 'Intelligence is the ability to adapt to change.',
    photo: '/assets/posts/7.jpg',
    date: '1 day ago',
    userId: 7,
    like: 312,
    comment: 55,
  },
  {
    id: 8,
    desc: 'pyschology is the study of the mind and behavior',
    photo: '/assets/posts/8.jpg',
    date: '3 days ago',
    userId: 8,
    like: 2,
    comment: 19,
  },
  {
    id: 9,
    desc: 'Love For All, Hatred For None.',
    photo: '/assets/posts/9.jpg',
    date: '3 days ago',
    userId: 9,
    like: 34,
    comment: 23,
  },
  {
    id: 10,
    desc: 'jumping in the sky',
    photo: '/assets/posts/10.jpg',
    date: '5 days ago',
    userId: 10,
    like: 32,
    comment: 9,
  },
]
